name: update

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # daily

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: batch
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          .github/workflows/update.sh
